### ISSUE TITLE
dataset containing a url to a site that seems to be having internal server issues currently.

### ISSUE THREAD

**Issue by VishalBora01752** [Silver15987/user-hunter#2]
One of the URLs in the dataset seems to be addressing a site that is facing internal server issues. Waiting for a minimum of 24 hrs. should give us a better insight into the situation.

The URL :
"https://{username}.newgrounds.com"

The link to the line:
https://github.com/Silver15987/user-hunter/blob/53d6d15e88ea4d3cc08a47044070e91be2aac337/src/website.json#L105

---------------------------------------------------------------------------------------------------------

The site seems to be having troubles opening:
https://github.com/Silver15987/user-hunter/blob/53d6d15e88ea4d3cc08a47044070e91be2aac337/src/website.json#L132

**Comment by Silver15987** [comment]
The following have been fixed by commit 53d6d15e88ea4d3cc08a47044070e91be2aac337.
